#Author:Galirus-Official
#Whatsapp :085732779537

#Note : Tolong jangan di Ubah jika tidak 
#mau terjadinya ERROR,mau recode ? 
#belajarlah lu pikir gua ga belajar ? 
#hacker kok recode ! seorang HACKER 
#tidak mengaku dirinya HACKER jadi 
#sadar diri gobvlok :v





z="
";cBz='lahk';CDz=' go.';aBz='e ny';OCz='hon3';az='[1;3';Jz='p 2"';fDz='p 1';hDz='UKA ';yBz='DULE';tz='an T';SCz='h ph';iCz='pycr';Iz='slee';ZBz='ckag';Gz=' 1"';JDz='t" ]';TCz='p gi';NDz='& ap';RCz=' bas';KCz='y';vBz='INST';Oz='m="\';eCz='fake';ODz='t up';LCz=' ins';rCz='cd';sBz='sudo';RDz='pyth';PBz='etik';mz='age ';Uz='k="\';jBz='S-40';ACz='/PAC';xBz='h MO';Bz='e"';VCz='et';pCz='rama';kBz='4]==';sCz='cd T';NBz='NTER';nDz='ER I';pz='a Ba';lz='Pack';ICz='pgra';mDz=' BEN';fBz='read';CCz='p 2';Hz='ss="';Pz='033[';JBz='na$b';DDz='sh';eDz=' ]';UDz='on';GDz='$apa';MBz='ETHU';SBz=' sud';wBz='ALL$';PCz='hon2';gBz=' -p ';Lz='"sle';eBz='$m n';lBz='=> "';EDz='elif';lDz='YANG';dBz='an k';ECz=' upd';oCz='colo';VBz='h me';Az='q="-';sz='unak';BDz='bash';jz='Inst';vCz='-r r';qz='ru M';MCz='tall';ABz='a pe';YBz='l pa';TBz='ah p';Sz='h="\';fCz='_usr';iBz='LIRU';GCz='&& a';HDz='h" =';FCz='ate ';oBz='if [';tBz='" ]';wCz='equi';dz='1;37';BCz='KAGE';hCz='t';oz=' Jik';QDz='e -y';XDz=' wge';Fz='leep';bCz='hani';XCz='inst';tCz='OOLS';FDz=' [ "';cz='p="\';Wz='b="\';hz=' $q ';FBz='tik$';BBz='nggu';cDz='m';Tz='1;32';nz='Dulu';WDz=' git';mBz=' apa';yz=' and';LBz='ux/N';jCz='ypto';ZDz='boar';IBz='jika';Nz='"';bBz='a si';Kz='sss=';rBz=' = "';uBz='then';aDz='d';bDz=' tqd';Rz='m"';dDz=' "n"';VDz=' php';uCz='V2';uz='ools';NCz=' pyt';JCz='de -';RBz='udo"';gz='echo';IDz=' "ap';CBz='na T';mCz='keyb';OBz='$k k';WBz='ngin';qBz='pah"';jDz='S"';YDz=' key';SDz='on3 ';DBz='ermu';MDz='te &';nCz='oard';cCz='ze b';qDz='fi';iDz='TOOL';ZCz='ests';WCz='pip ';nBz='h';QBz='$m s';yCz='nts.';LDz='upda';KBz=' Lin';Dz='cho"';oDz='SINY';fz='r';HBz='t"';EBz='x Ke';kDz='else';Cz='e="e';bz='6m"';xz='Jika';pDz='A"';XBz='stal';gCz='agen';lCz='rich';YCz='requ';aCz=' mec';Yz='bl="';QCz='hon';DCz=' apt';vz=' Ini';Mz='ep 3';wz='$k "';Xz='1;34';UCz='t wg';GBz='m ap';xCz='reme';ADz='txt';Vz='1;33';Zz='\033';Ez='s="s';HCz='pt u';KDz='apt ';PDz='grad';UBz='erna';ez='clea';gDz='MEMB';qCz='tqdm';kCz='dome';hBz='"[GA';pBz=' "$a';dCz='s4';TDz='on2 ';iz='$bl"';Qz='1;31';kz='all ';rz='engg';
eval "$Az$Bz$z$Cz$Dz$z$Ez$Fz$Gz$z$Hz$Iz$Jz$z$Kz$Lz$Mz$Nz$z$Oz$Pz$Qz$Rz$z$Sz$Pz$Tz$Rz$z$Uz$Pz$Vz$Rz$z$Wz$Pz$Xz$Rz$z$Yz$Zz$az$bz$z$cz$Pz$dz$Rz$z$ez$fz$z$gz$z$gz$hz$iz$jz$kz$lz$mz$nz$oz$pz$qz$rz$sz$tz$uz$vz$Nz$z$gz$hz$wz$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$GBz$HBz$z$gz$hz$wz$IBz$yz$ABz$BBz$JBz$KBz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$z$gz$hz$wz$IBz$SBz$TBz$UBz$VBz$WBz$XBz$YBz$ZBz$aBz$bBz$cBz$dBz$PBz$eBz$Nz$z$fBz$gBz$hBz$iBz$jBz$kBz$lBz$mBz$nBz$z$oBz$pBz$qBz$rBz$sBz$tBz$z$uBz$z$gz$hz$wz$vBz$wBz$xBz$yBz$ACz$BCz$Nz$z$Iz$CCz$z$sBz$DCz$ECz$FCz$GCz$HCz$ICz$JCz$KCz$z$sBz$DCz$LCz$MCz$NCz$OCz$NCz$PCz$NCz$QCz$z$sBz$DCz$LCz$MCz$RCz$SCz$TCz$UCz$VCz$z$WCz$XCz$kz$YCz$ZCz$aCz$bCz$cCz$dCz$z$WCz$XCz$kz$eCz$fCz$gCz$hCz$z$WCz$XCz$kz$iCz$jCz$kCz$z$WCz$XCz$kz$lCz$z$WCz$XCz$kz$mCz$nCz$z$WCz$XCz$kz$oCz$pCz$z$WCz$XCz$kz$qCz$z$rCz$z$sCz$tCz$uCz$z$WCz$XCz$kz$vCz$wCz$xCz$yCz$ADz$z$BDz$CDz$DDz$z$EDz$FDz$GDz$HDz$IDz$JDz$z$uBz$z$KDz$LDz$MDz$NDz$ODz$PDz$QDz$z$KDz$XCz$kz$RDz$SDz$RDz$TDz$RDz$UDz$z$KDz$XCz$kz$BDz$VDz$WDz$XDz$hCz$z$WCz$XCz$kz$YCz$ZCz$aCz$bCz$cCz$dCz$z$WCz$XCz$kz$eCz$fCz$gCz$hCz$z$WCz$XCz$kz$iCz$jCz$kCz$z$WCz$XCz$kz$lCz$YDz$ZDz$aDz$z$WCz$XCz$kz$oCz$pCz$bDz$cDz$z$rCz$z$sCz$tCz$uCz$z$WCz$XCz$kz$vCz$wCz$xCz$yCz$ADz$z$BDz$CDz$DDz$z$EDz$FDz$GDz$HDz$dDz$eDz$z$uBz$z$Iz$fDz$z$gz$hz$wz$gDz$hDz$iDz$jDz$z$Iz$CCz$z$rCz$z$sCz$tCz$uCz$z$BDz$CDz$DDz$z$kDz$z$gz$hz$wz$lDz$mDz$nDz$oDz$pDz$z$Iz$CCz$z$qDz"