#Author:Galirus-Official
#Whatsapp :085732779537

#Note : Tolong jangan di Ubah jika tidak 
#mau terjadinya ERROR,mau recode ? 
#belajarlah lu pikir gua ga belajar ? 
#hacker kok recode ! seorang HACKER 
#tidak mengaku dirinya HACKER jadi 
#sadar diri gobvlok :v


z="
";Yz='bl="';kCz='reme';KBz=' Lin';EDz='pyth';hBz='then';sCz='$apa';XCz='dome';Hz='ss="';VBz='LIRU';nBz='KAGE';TCz='agen';pz='a Ba';UBz='"[GA';Sz='h="\';yz=' and';ez='clea';Vz='1;33';Lz='"sle';lCz='nts.';iBz='INST';tz='an T';Ez='s="s';aCz='oard';eCz='cd';Jz='p 2"';vBz='de -';Kz='sss=';DDz='e -y';Cz='e="e';Az='q="-';Wz='b="\';NDz='d';Uz='k="\';ECz=' bas';UDz='SINY';tBz='pt u';jz='Inst';dBz='pah"';SCz='_usr';oBz='p 2';GBz='m ap';ADz='& ap';BDz='t up';rBz='ate ';uz='ools';fBz='sudo';Zz='\033';lBz='DULE';ICz='et';Tz='1;32';HCz='t wg';vz=' Ini';QDz='else';dz='1;37';Mz='ep 3';uCz=' "ap';ZBz=' apa';OCz='hani';MDz='boar';jBz='ALL$';HDz='on';Xz='1;34';Qz='1;31';QCz='s4';DBz='ermu';ABz='a pe';tCz='h" =';TBz=' -p ';mCz='txt';LDz=' key';sBz='&& a';fCz='cd T';OBz='$k k';XBz='4]==';iz='$bl"';bBz='if [';Bz='e"';NCz=' mec';Iz='slee';PDz='m';Dz='cho"';BBz='nggu';yCz='te &';KDz=' wge';KCz='inst';eBz=' = "';DCz='hon';Rz='m"';Oz='m="\';kz='all ';iCz='-r r';vCz='t" ]';wBz='y';WCz='ypto';cz='p="\';FBz='tik$';MCz='ests';az='[1;3';jCz='equi';FCz='h ph';FDz='on3 ';HBz='t"';nz='Dulu';hz=' $q ';bCz='colo';gCz='OOLS';qz='ru M';WDz='fi';rCz=' [ "';fz='r';ACz=' pyt';VCz='pycr';nCz='bash';LBz='ux/N';Fz='leep';xCz='upda';UCz='t';LCz='requ';oz=' Jik';bz='6m"';cBz=' "$a';RBz='udo"';YBz='=> "';uBz='pgra';mz='age ';kBz='h MO';pCz='sh';MBz='ETHU';mBz='/PAC';Gz=' 1"';gBz='" ]';CBz='na T';aBz='h';xBz=' ins';CCz='hon2';Nz='"';xz='Jika';sz='unak';ZCz='keyb';CDz='grad';cCz='rama';GCz='p gi';JDz=' git';RDz='YANG';SDz=' BEN';JCz='pip ';EBz='x Ke';NBz='NTER';rz='engg';QBz='$m s';dCz='tqdm';PCz='ze b';wz='$k "';ODz=' tqd';WBz='S-40';IDz=' php';PBz='etik';qBz=' upd';RCz='fake';wCz='apt ';oCz=' go.';VDz='A"';YCz='rich';lz='Pack';TDz='ER I';gz='echo';JBz='na$b';GDz='on2 ';Pz='033[';BCz='hon3';yBz='tall';SBz='read';IBz='jika';hCz='V2';qCz='elif';pBz=' apt';
eval "$Az$Bz$z$Cz$Dz$z$Ez$Fz$Gz$z$Hz$Iz$Jz$z$Kz$Lz$Mz$Nz$z$Oz$Pz$Qz$Rz$z$Sz$Pz$Tz$Rz$z$Uz$Pz$Vz$Rz$z$Wz$Pz$Xz$Rz$z$Yz$Zz$az$bz$z$cz$Pz$dz$Rz$z$ez$fz$z$gz$z$gz$hz$iz$jz$kz$lz$mz$nz$oz$pz$qz$rz$sz$tz$uz$vz$Nz$z$gz$hz$wz$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$GBz$HBz$z$gz$hz$wz$IBz$yz$ABz$BBz$JBz$KBz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$z$SBz$TBz$UBz$VBz$WBz$XBz$YBz$ZBz$aBz$z$bBz$cBz$dBz$eBz$fBz$gBz$z$hBz$z$gz$hz$wz$iBz$jBz$kBz$lBz$mBz$nBz$Nz$z$Iz$oBz$z$fBz$pBz$qBz$rBz$sBz$tBz$uBz$vBz$wBz$z$fBz$pBz$xBz$yBz$ACz$BCz$ACz$CCz$ACz$DCz$z$fBz$pBz$xBz$yBz$ECz$FCz$GCz$HCz$ICz$z$JCz$KCz$kz$LCz$MCz$NCz$OCz$PCz$QCz$z$JCz$KCz$kz$RCz$SCz$TCz$UCz$z$JCz$KCz$kz$VCz$WCz$XCz$z$JCz$KCz$kz$YCz$z$JCz$KCz$kz$ZCz$aCz$z$JCz$KCz$kz$bCz$cCz$z$JCz$KCz$kz$dCz$z$eCz$z$fCz$gCz$hCz$z$JCz$KCz$kz$iCz$jCz$kCz$lCz$mCz$z$nCz$oCz$pCz$z$qCz$rCz$sCz$tCz$uCz$vCz$z$hBz$z$wCz$xCz$yCz$ADz$BDz$CDz$DDz$z$wCz$KCz$kz$EDz$FDz$EDz$GDz$EDz$HDz$z$wCz$KCz$kz$nCz$IDz$JDz$KDz$UCz$z$JCz$KCz$kz$LCz$MCz$NCz$OCz$PCz$QCz$z$JCz$KCz$kz$RCz$SCz$TCz$UCz$z$JCz$KCz$kz$VCz$WCz$XCz$z$JCz$KCz$kz$YCz$LDz$MDz$NDz$z$JCz$KCz$kz$bCz$cCz$ODz$PDz$z$eCz$z$fCz$gCz$hCz$z$JCz$KCz$kz$iCz$jCz$kCz$lCz$mCz$z$nCz$oCz$pCz$z$QDz$z$gz$hz$wz$RDz$SDz$TDz$UDz$VDz$z$Iz$oBz$z$WDz"